Feat api template
Flygrounder/rss-reader pull request #7
Opened 2022-09-11 20:05 UTC by Flygrounder

2022-09-13 17:09 UTC, AlexisOMG commented on src/backend/internal/api/api.go
> +		c.Status(http.StatusBadRequest)
Уверен, что это именно BadRequest, а не InternalServerError?

2022-09-13 17:20 UTC, AlexisOMG requested changes

2022-09-13 17:20 UTC, AlexisOMG commented on src/backend/internal/api/api.go
> +		c.Status(http.StatusBadRequest)
Уверен, что это именно BadRequest, а не InternalServerError?

2022-09-13 17:20 UTC, AlexisOMG commented on src/backend/internal/api/api.go
> +	}
```suggestion
	if err != nil {
	        c.Status(http.StatusBadRequest)
		return
	}
```

2022-09-13 17:20 UTC, AlexisOMG commented on src/backend/internal/api/api.go
> +	}
```suggestion
	if err != nil {
		c.Status(http.StatusBadRequest)
		return
	}
```

2022-09-13 17:32 UTC, Flygrounder commented on src/backend/internal/api/api.go
> +	}
![изображение](https://user-images.githubusercontent.com/16033061/189970519-79c66d11-413e-4b69-ba32-b63b711479a1.png)
https://gin-gonic.com/docs/examples/binding-and-validation/

2022-09-13 17:32 UTC, Flygrounder commented on src/backend/internal/api/api.go
> +	}
Вот тут справедливо

2022-09-13 17:43 UTC, AlexisOMG commented on src/backend/internal/api/api.go
> +	}
Асуждаю неявную логику

2022-09-14 05:31 UTC, AlexisOMG approved these changes

2022-09-14 05:32 UTC, merged